# Generated by Django 2.2.7 on 2019-12-05 12:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пунк відправлення')),
                ('arrival', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пунк прибуття')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Дистанція')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Додаткова інформація')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добвлено')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я'")),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-published'],
            },
        ),
    ]
